# Generated by Django 2.0.7 on 2018-07-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
