# Generated by Django 2.0.7 on 2018-07-16 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_user_app', '0002_users_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
