# Generated by Django 2.0.7 on 2018-07-16 20:16

import apps.its_user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_user_app', '0003_auto_20180716_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.CharField(max_length=255, validators=[apps.its_user_app.models.validate_email]),
        ),
    ]
