# Generated by Django 2.0.7 on 2018-07-16 20:27

import apps.its_user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_user_app', '0004_auto_20180716_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255, validators=[apps.its_user_app.models.length]),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=255, validators=[apps.its_user_app.models.length]),
        ),
    ]
