# Generated by Django 2.0.7 on 2018-07-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('desc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='its_courses.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
