# Generated by Django 2.0.7 on 2018-07-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its_courses', '0002_auto_20180718_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='course',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='its_courses.Course'),
        ),
        migrations.AlterField(
            model_name='desc',
            name='desc',
            field=models.TextField(),
        ),
    ]
