# Generated by Django 2.0.7 on 2018-07-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its_courses', '0004_auto_20180718_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='my_desc', serialize=False, to='its_courses.Course'),
        ),
    ]
