# Generated by Django 2.0.7 on 2018-07-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its_courses', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='courses',
        ),
        migrations.AddField(
            model_name='comment',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to='its_courses.Course'),
        ),
    ]
