# Generated by Django 2.0.7 on 2018-07-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its_dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='description'),
        ),
    ]
